### ISSUE TITLE
Add reqs for Worst Room in the Game right to top

### ISSUE THREAD

**Issue by blkerby** [vg-json-data/sm-json-data#1005]
I noticed this spot gave some trouble to a player recently: https://clips.twitch.tv/RudeTangibleSnakeSMOrc-ZZCZ-hE6Ynh-PVW3 (this was their last of several attempts, after which they gave up).

Some tech requirement should probably be added to avoid taking damage from the Pirate going from the right door to the top left door. Maybe canDodgeWhileShooting? Or canCarefulJump at least?

**Comment by osse101** [comment]
This link is very not obvious how to quickly and safely do the strat with no items.

The strat is to walk left into the step and shoot straight up, then climb out.  Maybe shoot a bit more to widen the gap.  And if you do this super quick the pirate will turn around early and shoot, not that that really gets in the way.
I timed it with angle shots from the door which is a little faster, but uses `canStopOnADime`.  And gets closer to the pirate.  But has a bigger hole to jump into.

The player's issue is that they were jumping into the room which triggered the pirate to attack.  Then still had time to dodge with a crouch, but its hectic. 

Something should be added to this even if its just make it a Medium notable.
