### ISSUE TITLE
Add unique IDs to tech and notable strats

### ISSUE THREAD

**Issue by blkerby** [vg-json-data/sm-json-data#1008]
It would be useful to have a unique "id" on each tech and notable strat (similar to what we have on rooms & nodes). This can make it possible for randomizers to store user-customized presets in a stable way that won't be broken by renaming techs/strats. It seems good to use the same ID space for both tech and notables, to be able to handle a situation where a tech is converted to a notable or vice versa.

For reusable notable strats, the ID should exist at the level of the reusable, the same ID being shared across all the individual strats associated with it.

The idea is that once an ID is assigned, it should never be changed (unless the meaning of the tech/notable is changed to such an extent that we don't want it to be linked to the old version). If tech/strats are deleted it can leave gaps in the ID space and that's fine; there's no need for the IDs to be contiguous, and deleted IDs should not be reused.

We could maybe create a small file  "next_tech_id.txt" containing the next ID to be used, to help us keep track.

**Comment by kjbranch** [comment]
Partially addressed in #1599

**Comment by kjbranch** [comment]
This was completed in #1624 and #1640
