### ISSUE TITLE
Consider adding leniency for heated X-ray climb setups

### ISSUE THREAD

**Issue by blkerby** [vg-json-data/sm-json-data#1018]
When doing an X-ray climb setup requires going into a heated room, we may want to add helpers to provide some leniency, similar to what we did with gate glitching? I assume the expected number of attempts (and in some cases heat frames per attempt) could depend on the type of setup: left side, right side, right side from water, and shinespark deep stuck, so we might need multiple helpers.

**Comment by osse101** [comment]
There is a different frame window depending on the door stuck.  

Our basic XRay climb door stuck is pretty generous, but also most people aren't going to be experts at it; you have to study up on the frame window.  But it gets pretty reliable.  

Dash state doorstuck I find doesn't take that many attempts to get and knowing that this is possible used to be the larger problem.

Shinespark door stuck is frame perfect but in a controllable way.  Its just hard to get in one attempt for that reason alone.

GMode doorstuck is a GMode leniency problem.

Underwater doorstuck is ~double frame perfect and you can't expect to get it right away.

So I would say all of these should expect taking multiple attempts.  `canXRayClimb` feels like you can do it reliably, but not at the same skill tier that the tech is on.  Shinespark and underwater may want to be given heatproof.  
And if there is an easily accessible farm spot in the non-heated room, adding leniency doesn't seem necessary.
