### ISSUE TITLE
Add reqs for Metroid rooms with Screw Attack

### ISSUE THREAD

**Issue by blkerby** [vg-json-data/sm-json-data#1019]
Currently the logic has that Screw Attack makes avoiding Metroid damage free. This doesn't seem right because it is still non-trivial to avoid the Metroids even with Screw. Maybe we could add a tech requirement such as "canCarefulJump" or "canDodgeWhileShooting". I would lean toward "canDodgeWhileShooting", since although there's no shooting involved, it's more than just one careful jump, and feels more like Hard difficulty (for instance, it seems at least as hard as getting past the Alcoons in Crateria Power Bomb Room which requires canDodgeWhileShooting). I think players on Medium generally would not expect going through Metroid rooms to be required with only Screw. Example seed from last night (on Medium-ish settings) which prompted this: https://www.twitch.tv/videos/1902529487.

Even if the player fails to completely avoid the Metroids, Screw can help with reducing the damage since no damage is taken while Screw is active. But players on low difficulty settings are unlikely to be aware of this fact, so I'm not sure this should necessarily factor in.

**Comment by osse101** [comment]
Adding `canDodgeWhileShooting` fits.

There are some other strats to rethink too:

Taking a Rinka hit to reduce mertroid damage.  Its not something you think about at as a strat to get through the room, more of an emergance play.  And as a way to `hitBox` a metroid, you should be using `canMetroidavoid` instead.  So I think the Rinka hit strat can be removed.

Using PBs to kill Metroids.  Seems less obvious than avoiding damage with Screw.

**Comment by kjbranch** [comment]
These rooms, including PB strats, were improved significantly in #1458 refined a bit more in #1534
