### ISSUE TITLE
Collect Items During a Strat? (for Big Pink remote acquire g-mode)

### ISSUE THREAD

**Issue by kjbranch** [vg-json-data/sm-json-data#1086]
Remote acquiring items while in g-mode has been regularly handled by setting an obstacle cleared and then using that to return. One thing to be careful with, is that the requirements to get back can't use the item itself, so all of the requirements are included on the strat getting there, which sets the obstacle cleared.

Big Pink is particularly difficult, because there are two items that can be obtained (10, 11) and many doors that can be started from (2, 3, 6, 8) and locations to go after obtaining one or both items (1, 4, 8, 12). Setting the requirements on the obstacle before obtaining the item is not possible, because it depends where you go, so this can only be remedied with making a ton of obstacles. However, because this room already has many obstacles and links, the room is also already very slow to compute, and adding more obstacles will make this much worse. Even if this were possible, it would still have major problems: go to item 1 setting the remote acquire obstacle, unmorph and get item 2, return to 1, and the obstacle will still be set for remote acquiring with artificial morph.

The only way I can think of solving this is by adding a way to obtain an item while performing a strat, similar to how obstacles are cleared. This is likely a pain to implement, but it could be used in other locations to simplify the logic as well. Reducing the number of obstacles and possibly nodes in some instances. If this is worth doing, it may also be worth considering adding a way to clear flags the same way.

**Comment by blkerby** [comment]
I like the idea of `remoteAcquireItem` being a node property rather than strat property. Node property would fit better with the randomizer implementation. Otherwise basically the randomizer would need to create extra nodes for the endpoints of those strats. Extra nodes created by the randomizer create potentially confusing discrepancies between the sm-json-data and the randomizer logic pages, which would be nice to avoid.
