### ISSUE TITLE
Rework requirements in Crab Hole

### ISSUE THREAD

**Issue by blkerby** [vg-json-data/sm-json-data#1161]
This strat in particular should require something more than Medium tech, should be Very Hard I would think:

https://maprando.com/logic/room/CrabHole/2/1/SuitlessHiJump

**Comment by osse101** [comment]
HiJump + Ice are the requirements for VARIA so that would place it in Hard.
And the fast way to do the strat jumps from the right side ledge and gets a frozen enemy boost to get on top of a middle hole crab.  So there is no crouch, but maybe a downgrab.
