### ISSUE TITLE
Add Grapple Warping strats

### ISSUE THREAD

**Issue by blkerby** [vg-json-data/sm-json-data#1189]
Triggering a door transition while grappling results in Samus' position being overwritten after the transition, allowing the player to potentially warp to a distant part of the next room. Red Brinstar Fireflea Room is an example where you can exit the left door in this way. We could add a new pair of exit/entrance conditions to be able to model strats like this.

**Comment by osse101** [comment]
I think Red Brinstar Firefleas is the only room where you can do this.
Entrance/Exit conditions make sense.  The tech itself is very similar to a grappleClip but with a frame perfect moonwalk.
And the effect puts Samus on the leftmost room tile of the room.  And I forget if the room tile is on the top row, or in line with the door.  But there certainly are skips possible with a grapple warp.

**Comment by blkerby** [comment]
Bobbob created a playlist showing all the grapple teleport applications from Red Brinstar Firefleas: https://www.youtube.com/watch?v=g3jEO-WxvK0&list=PLUMF22jq7du0mfVSKbEZZhA1OaKH1Wtzh.

He also gave these notes about other setup locations (https://discord.com/channels/1053421401354285129/1053436236628496454/1208621382393532526):

> 
>     red brinstar firefleas left:  leftward transition, top left screen, 6 blocks from the left and 4 blocks from the top. we'll call it (6,4).
>     moat left:  leftward transition, top left screen, (8,3).
>     colosseum left:  leftward transition, top left screen, (4,13) or (4,14) [yes these can have different behavior where sometimes things work from one but not the other]
>     halfie climb top left:  leftward transition, one screen down from top left, (3,3) or (3,13) or (3,14).
>     draygon left:  leftward transition, one screen down from top left, (3,3) or (3,4).
>     halfie climb bottom left:  leftward transition, two screens down from top left, (3,3).
>     halfie climb top right:  rightward transition, top left screen, (13,13) or (13,14).
>     colosseum top right:  rightward transition, seven screens right of top left, (13,13) or (13,14).
>     colosseum bottom right:  rightward transition, seven screens right and one screen down of top left, (13,3).
>
