### ISSUE TITLE
Fix PCJR logic

### ISSUE THREAD

**Issue by blkerby** [vg-json-data/sm-json-data#1514]
Post Crocomire Jump Room appears to currently have an issue where if you come in from the right, break the speed blocks, and then go up to the item, it won't remember that the speed blocks are broken so you won't logically be able to go back to the right without Morph or some other way of breaking them.

I think the logic in this room could be simplified by removing node 4. It seems to be obsolete since obstacle "B" was added.

**Comment by kjbranch** [comment]
Resolved in #1551
