### ISSUE TITLE
Moat shinespark strats

### ISSUE THREAD

**Issue by blkerby** [vg-json-data/sm-json-data#1536]
It is possible to enter Moat from the right door with a shinecharge (or shinecharging), jump over the water, collect the item, and then spark back across to the right. This avoids the CWJ, which could be essential in a collectible walljump scenario. Variations would also be possible that end by sparking out either door. We could represent these strats by adding another obstacle to the room, similar to what we did with Screw Attack Room and Grapple Beam Room. Alternatively, it could be done in a simpler way now using the new `collectsItems` strat property, without needing to add an obstacle. The existing obstacle could probably also be removed in favor of using `collectsItems` as well.

Insomniaspeed video: https://discord.com/channels/1053421401354285129/1053436236628496454/1247939732776812565

**Comment by kjbranch** [comment]
Resolved in #1559
