### ISSUE TITLE
Add tools for notable strat user documentation

### ISSUE THREAD

**Issue by fdtaillefer** [vg-json-data/sm-json-data#286]
Right now, some of the strats have a description as part of their note.

What we should do is instead have a `description` property that explains the strat. Developer notes can remain in `note`

Additionally, we could add a property (or several) to link to an explanatory page or a demonstrative video. This could be a starting point to generate player documentation about notable strats.

**Comment by miketrethewey** [comment]
`crocomire` for linking to the associated http://crocomi.re page.
Example: https://crocomi.re/36
```
{
  "crocomire": 36
}
```

**Comment by kjbranch** [comment]
Closing this as the primary issue is solved and the secondary issue is also, or mostly solved as well:
- The note/devNote separation implemented some time ago solves the primary issue
- Map Rando is now hosting full quality videos (with input display) of the notable strats. These are viewable by clicking on an animated GIF on the strat pages. These should be easy to find as they are included using the same names as what is in the logic in this project. 

Another issue could be opened for directly linking the logic to the videos, if that is needed.
