### ISSUE TITLE
Add aqueduct bomb block strats

### ISSUE THREAD

**Issue by fdtaillefer** [vg-json-data/sm-json-data#309]
See https://youtu.be/z3QHBvBHOoo
Decide whether we really want to add the out-of-room setups, but there are others that are fully in-room.

**Comment by osse101** [comment]
https://youtu.be/wrTQcXC8EhE
This is pretty hard as a fall through the door moving left strat, but is fine for falling straight down if you unmorph to keep blue.

https://youtu.be/7sWKoYeA55U
This seems fine to add

There is a springball method like the spacejump one but seems to end with repeated unmorph-jumping to carry blue to the bomb blocks.  Worry about this strat after that tech is decided on.

I don't recall if there were any others.

**Comment by osse101** [comment]
Note these require low run speed.

**Comment by kjbranch** [comment]
Resolved in #1585 
Note that coming from the top door was added as a temporary blue chain instead of a speed ball.
