### ISSUE TITLE
Add a logical element to indicate that a door has to be opened

### ISSUE THREAD

**Issue by fdtaillefer** [vg-json-data/sm-json-data#325]
Sometimes, a strat requires positioning in a door's entry way, which requires the door to be opened beforehand.

This is relevant to know, because maybe a modification could make the door grey, or maybe the player isn't able to open that door.

We should add a logical element to describe that situation, and use it where relevant.

**Comment by fdtaillefer** [comment]
Known strats where this should be used:

- Boulder Room Doorsill Jump

**Comment by kjbranch** [comment]
- `Screw Attack Room Doorway Speedjump`
- `Screw Attack Room Doorway CWJ`

**Comment by kjbranch** [comment]
There may be some need to expand on this to indicate how a door is unlocked. 
- For many strats it doesn't matter which type of door exists there, but just that it is openable:
  - The need to stand in the doorsill `Boulder Room Doorsill Jump` and `Butterfly Room Careful Jump`
  - Extending a runway by opening an opposite side door
- Many other strats work only if the door is blue or red/green with a Super (not red with 5 missiles or yellow):
  - Cross room jumps through the door, like Oasis and Glass Tunnel
  - Some shinecharge strats where the runway is inaccessible from the door, like Early Supers
  - Most 3-room shinecharge strats
