### ISSUE TITLE
Fill out strat failure data

### ISSUE THREAD

**Issue by fdtaillefer** [vg-json-data/sm-json-data#328]
Once #285 is resolved, we'll have a way to define strat failures.

That will allow us to go through the model and define the consequences of failing strats.

**Comment by kjbranch** [comment]
There are practically an unlimited number of ways to fail a strat - falling into a softlock, missing a timing forcing a need to reset a room, taking extra damage, moving non-optimally to take more heat frames, etc.

This data doesn't seem feasible to include, and it isn't clear how it can be used.
