### ISSUE TITLE
Define the risk of falling to a node when spawning in a room

### ISSUE THREAD

**Issue by fdtaillefer** [vg-json-data/sm-json-data#329]
We already have the `spawnAt` property on nodes, to indicate that Samus winds up at another node when entering a room through a specific node.

We are missing an additional piece of info that indicates the risk of immediately falling to another node. That is something the player can position to avoid if they know the layout.

This can mainly be used for vertical doors that are above a platform, but the platform is narrower than the door. The top right door in Fish Tank and the top door in Mt. Everest are exemples of this situation.

**Comment by kjbranch** [comment]
There are actually relatively few entrance conditions that prevent Samus from landing on these platforms, and it doesn't seem like there are cross-room strats that force them (except maybe high-speed moonfalls to skip a doorcap). If there are, they will need to be modeled with an entrance condition and can be dealt with accordingly.

For low skill levels it is possible to accidentally miss the platform, but it is unclear how that information could be used, and there are many other ways for players to get stuck which would not be feasible to model.

For any other skill levels, it is possible to quickly react on room entry to correct and land on the platforms. It is also good practice to enter downward doors with caution, as many of them lead into one-way transitions where Samus can't return without movement items.
