### ISSUE TITLE
Reduce duplication in Plasma Room

### ISSUE THREAD

**Issue by fdtaillefer** [vg-json-data/sm-json-data#459]
See https://github.com/miketrethewey/sm-json-data/pull/454.

This introduced two separate strats where you kill one pirate, which duplicates that logic. We have two options here:
- Add a node to represent one pirate killed
- Add a general concept where reusable strats (scoped to one room) can be defined. This would involve a `reusableStrats` property on the room and a `reusableStrat` logical element. This is a breaking change as consumers need to understand this, so this cannot be done before we have at least done an initial release version, so that we can include this change in a new version with release notes.

**Comment by kjbranch** [comment]
This is something that has occurred in many rooms and may be worth considering, but it is closed as the ideas in #464 replace it.
