### ISSUE TITLE
Find a way to separate flawless execution from more forgiving requirements

### ISSUE THREAD

**Issue by fdtaillefer** [vg-json-data/sm-json-data#462]
Many strats do not require any energy loss because it's possible to execute them cleanly, but they can be difficult.

Perhaps we could add a new `canMoveFlawlessly` tech ("execution" can be ambiguous, and we want to hopefully not have confusion with the `inputs` terminology in some modifier techs introduced by #463) and use that as a requirement, with energy costs as an alternative. Then players who don't want to be required to execute flawlessly could still apply those strats but in a more forgiving context.

**Comment by kjbranch** [comment]
This has been solved by adding the use of different difficulty tech to strats, including: `canCarefulJump`, `canTrickyJump`, `canDodgeWhileShooting`, etc.
