### ISSUE TITLE
Complex Strats to Avoid canWalljump

### ISSUE THREAD

**Issue by kjbranch** [vg-json-data/sm-json-data#514]
Now that canWalljump is being implemented throughout the game, more complex strats can be added to avoid this requirement. Common examples include shinesparks and spring ball jumps, but more obscure examples exist: 
- Pink Hopper Room - clipping a missile to trigger the elevator.
- Sponge Bath - reserve tank double hit

Although these very unlikely to be used by players who have turned off canWalljump, they could be used in a hack that disables the wall jump ability.

**Comment by osse101** [comment]
Precathedral left door
Ice - Stand near the door and watch a nova do its loop until it starts climbing back up to the door from below where you can climb using it
Morph tunnel - The intended way with morph and bomb/pb/springball/nova boost
