### ISSUE TITLE
Add lavaFrames to strats with Gravity Suit

### ISSUE THREAD

**Issue by osse101** [vg-json-data/sm-json-data#663]
It can't be assumed that Gravity gives full lava protection so the lavaFrames value should be added.  Gravity still enables faster movement in lava so the strat is still separate from Gravityless.
Rooms like

- Volcano Room
- Lava Dive
- Spiky Acid Spikes Tunnel
- Norfair Reserve Room potentially
- Rising Tides potentially

**Comment by kjbranch** [comment]
I believe those are all of the strats that need to be edited, except possibly also the Rising Tide, if it saves energy.

**Comment by osse101** [comment]
Rolling through lava in reverse Rising Tide is the recommended way to do the room in randomizers.
In forward Rising Tide the lava doesn't rise fast enough to make a difference.

**Comment by kjbranch** [comment]
I believe this is complete, however `lavaPhysicsFrames` should also be considered. The only two strats that use them are Gravity jumps in the Lava Dive Room. I think these frames could be significantly lowered by turning gravity back on mid jump.

**Comment by osse101** [comment]
I forgot there was `lavaPhysicsFrames`.  
I find the walljumps harder if I turn gravity back on, but some do turn it back on to save health.

I think norfair reserve can use a revamp and would include lava strats.  You move through the lava pretty fast with speed off and don't need to think about platforming.
