### ISSUE TITLE
Add notable strat for Metroid Room 4

### ISSUE THREAD

**Issue by blkerby** [vg-json-data/sm-json-data#714]
Getting through this room itemless in either direction seems to be much harder than the other three Metroid rooms. So it may sense to add a notable strat for it (then in Map Rando we can bump it up to a higher difficulty tier).

**Comment by osse101** [comment]
M4 top down needs a preplanned strat and that can be notable with a note.
M4 bottom up takes a strategy plus practicing the room, and that makes it a harder difficulty.

M2 bottom up has a metroid in your face and maybe is ok as it is.

M1 can be looked at again for avoiding metroids plus using a weak movement item to cross the lava.

**Comment by kjbranch** [comment]
There should also be considerations for PB kills. Which ones are particularly difficult?
