### ISSUE TITLE
Tech for using a frozen enemy to clip one pixel into the wall

### ISSUE THREAD

**Issue by osse101** [vg-json-data/sm-json-data#720]
Situations are starting to pop up where we want to clip horizontally into a wall 1 pixel, for XRay climbing, for GMode or for escaping a sand pit.

It would be the same tech used in `canIceZebetitesSkip` and `canWallIceClip` so we can think about how to integrate those.

**Comment by kjbranch** [comment]
`canWallIceClip` was edited slightly in #918. 

I wonder if it would make more sense to make `canWallIceClip` general enough to be used in all of these except for the Zeb skip, and then combine the various Zeb skips together?

**Comment by osse101** [comment]
`canWallIceClip` should be general enough as it is.

zebskip = rinka spawns 1 pixel in the wall so you freeze it at spawn and attach to it.
sand escape = enemy moves 1 pixel into wall so you freeze it at the right time and attach to it.
butterfly door clip = enemy moves 1 pixel further into the wall than samus so you freeze and attach to it over and over.
beetom xray climb = put the enemy 1 pixel from the wall and use another enemy to make samus attach to the frozen beetom

**Comment by osse101** [comment]
Well rinkas wouldn't be a case for `trickyUseFrozenEnemies`, but the rest can be grouped under the tech as is.
