### ISSUE TITLE
Using Frozen Enemies as Runway

### ISSUE THREAD

**Issue by osse101** [vg-json-data/sm-json-data#850]
Enemies can be frozen pixel perfectly to be the same height as runway and then you can run on top of them.  Most cases should be wallcrawlers, adding 1 tile of runway.  Farm bugs have a few spots where they can fly into a good position.  Beetom/mochtroids are going to be hard to control and TAS can line up multiple in a row, but that is not realistic.  Metroids would be even harder.

https://www.twitch.tv/jooniejoone/clip/MildScaryMilkDoritosChip--TQOYewukvbada0i

**Comment by kjbranch** [comment]
This was added and implemented in Brinstar in #1327.
- [x] Crateria (#1350)
- [ ] Wrecked Ship
- [ ] Maridia
- [ ] Norfair
- [ ] Tourian
