### ISSUE TITLE
Crystal Flash Node Property

### ISSUE THREAD

**Issue by kjbranch** [vg-json-data/sm-json-data#932]
Add a new property to nodes which indicates the requirements to CF at that node.

Things to consider: [Some of these are probably not worth modeling]
- Requirements should be able to include general requirements (ways to kill enemies or have enemy obstacles cleared)
- Damaging environmental effects need to apply before and after the CF (heat/acid/lava frames before, and CF might not fill Samus with a lot of tanks in lava or acid)
- CF can also clear obstacles (enemies, bomb blocks, yellow doors)
- CF can be done with 1 less PB in some instances

**Comment by osse101** [comment]
CF with 10pbs would need some kind of tech indicating advanced farming strat.  Its tricky to get the sequence of motions without practice.  But I've seen it done in frog speedway, Kronic Boost room, Caterpillar room.  Any room with near guaranteed pb drops, and a way to stay aligned with the exploding power bomb, by jumping straight up and down, or placing it in a corner. 

More nodes should be added to some rooms.  Lava dive mainly, also long straight rooms.  

Non heated rooms would need to allow CFs; as ways to gain full health or setup a GMode trick.

Can put it on the GT fight in canSafeSpotGT notable strats.

**Comment by kjbranch** [comment]
Closing this, as the CF strats were added in a different way. Some of these issues could still apply, but may or may not be worth adding. A new issue could be created for some of the remaining missing strats.
