### ISSUE TITLE
Missing Strats Crateria Central

### ISSUE THREAD

**Issue by kjbranch** [vg-json-data/sm-json-data#993]
Here is bobbob's notes for missing strats:
(The discussion starts here: https://discord.com/channels/445948207638511616/534430696635367444/1133140860427579606)

- [x] Landing Site
  - [x] 3 to 1:  the speed+morph bounceball strat doesn't need hjb. release jump (good visual cue with background), and morph on descent.
  - [x] 3 to 1:  with just speed (and items to get through rest of bombwall), there is arguably a health-saving strat if walljumps aren't in logic: it avoids shinesparking up there. this would only be relevant if, e.g., bottom right door wraps around to top right door, and top left door leads somewhere inaccessible that needs energy.
  - [x] 4 to 1:  Speed+HiJump+Spring Ball Jump:  Same as the blue space jump strat. Not too relevant, with speedy jump from 4 to 3 and bounceball from 3 to 1.
  - [x] 4 to 1:  Speed+Spring Ball Jump:  Same as above, but needs precise speed value (can be done entirely in-room). With the 3 to 1 bounceball above, it is just health-saving the shinespark to 3.
  - [x] 4 to 1:  Speed+HiJump+Tank:  Shinespark, no short charge, charge from ground, climb the left side quickly with walljumps. Probably not relevant, since climbing that fast is harder than short charging.
  - [x] 4 to 3:  XRay+CF:  Get normal stuck in the door, and then CF past the slope. To CF past a slope, you x-ray climb up to the slope (it will push you down, so no threat of going too high or anything), then auto-spinjump towards the door (to start holding jump, you can do it while holding x-ray). Then morph, CF, and keep x-ray climbing. Note this doesn't seem to work at most slopes, so each slope kind of has to be individually tested...
  - [x] 4 to 3:  Just a small recommendation, to change the helper to some sort of "canDeepStuck". There are other methods of deep stuck that could be added at some point, and then it would be really easy to.
  - [x] 2 (to 8) to 4:  Getting to 4 isn't free (walljump-less logic). Requires g-mode morph (as no plms to overload), 1 pb, or ibj. or the cool bomb+spring tech, i guess. note this should just be from 2, since getting to 4 from 3 is free and from 1 already has it's own strat (as it doesn't need g-mode morph).

- [x] Parlor
  - [x] 5 to 8:  Morphless g-mode-less alcatraz escape. this is the same as the ice clip strat, but instead of using an unmorph to enable xray usage you instead kill an enemy with grapple. i have this clip:  https://www.youtube.com/watch?v=FKe0fLU32Ak
    - [x] (note an r-mode clip would also work, but as there are no farming enemies this needs r-tanks > e-tanks. arguably, there could be a g-mode morph strat, which is done to be able to CF, and then can use the direct g-mode as r-mode to then clip out...)

- [x] Climb
  - [x] 1 to 3:  Is this missing a canComeInCharged to diagonally shinespark the top bomb block? This wouldn't need runway down below, and uses a lot less energy.
  - [x] 2 to 4:  Temp blue suit doesn't need x-ray, if you have hi-jump or spring ball jump. This needs a smaller runway: you need to at least finish before the earlier lowest platform (i think). Note with spring ball jump, you need fairly tight timing to not hit the platform.
  - [x] 3 to 6:  A speedball should work without spring. I haven't tested this, since vanilla doesn't have a good runway. However, it has better geometry than 4 to 6, which i have tested, see below.
  - [x] 3 to 6:  Temp Blue + Spring:  Are you all modeling carrying a temp blue into a 1-tile tall tunnel like this? I think it is in logic in other places. So this would be an alternative to the speedball.
  - [x] 4 to 6:  Speedball (in response to devnote, without spring). The speed value that works is pretty close to a "perfect 1-tap short charge", and then aim down just before hitting the low ceiling so you can clear it. Unsure how precise it really is.
  - [x] 4 to 6:  Temp Blue + Spring, similar to 3 to 6.
  - [x] 5 to 3:  X-Ray + Screw to break bomb block. The height to break the bomb block is fairly precise. A fairly long climb.
  - [x] 5 to 4:  X-Ray + Screw to break bomb block, like 5 to 3. A pretty short climb, but also less notable with moonfall+screw being an option.

- [x] Crateria Supers
  - [x] 1 to 3, and then falling to 5: Damage Boost Speedkeep: https://streamable.com/quk24e
this shows the minimal speed i got to work, of 5.2000. this needs the smallest 1-tap at the start, to actually have blue; the runway could be ever so slightly shorter with a stutter, but this is fairly close to minimal runway needed. it's easier with higher speeds.
to actually do the speedkeep, it is at least somewhat precise (you can damage boost and fail to keep blue, but i get it so often that it feels like it can't be frame perfect). so you press backwards (with jump held), possibly frame perfectly, and then in this case immediately release backwards and hold down (if you don't aim down, you'll hit the wall: it is that close to not working). then speedball through.

- [x] Pit Room
  - [x] 2 to 3:  Speed+Morph. Temp blue strat. You have it from the left, so why not from the right? (because it is considerably harder.) note space or spring may make it easier, just to help deal with the pirates: i found it easier, but who knows what that means. also morph is always required for it, unlike from left.
  - [x] 2 to 3:  G-mode with pbs. You have the trade-off of (4 pbs) <-> (3 pbs + 1 hit). There is also (2 pbs + 4 hits). This is relevant since if you g-mode immobile from the right with 99 energy, then you can get hit by pirate (1 hit), then do this strat (4 hits) and survive, so only use 2 pbs. since you can farm energy easily from pirates, using energy should be preferable. however, note this strat is precise:  wall pirate boost you to first pillar, wall pirate jumps to other side and boosts you to platform, use i-frames to position to left of platform pirate to get boosted over to pillar, then pb boost into the next pirate to get enough height that you bounce off the platform, and use this bounce to get to next pillar. yes, i tested this in g-mode, and it does work even with laser concerns.

- [x] Crateria Supers
  - [x] This is a fairly complicated room. so to keep this from being flooded, i just made a quick pastebin:  https://pastebin.com/DWjmFQwN

**Comment by osse101** [comment]
`4 to 1: Speed+Spring Ball Jump` - Hard enough that shortcharge or bounceball the blocks away and refill, then normal springball jump up is a better option.
`4 to 1: Speed+HiJump+Tank` - Spark to top, then spark blocks away and refill.  Then normal speed jumps to gauntlet.
`change the helper to some sort of "canDeepStuck"` - Helpers are really limited when they need to include a Node number.

**Comment by osse101** [comment]
Pit Room
`You have the trade-off of (4 pbs) <-> (3 pbs + 1 hit). There is also (2 pbs + 4 hits)` - The first damage boost is the hardest part so the 3 hit (3 hits are in the description) strat is fine to add.  But the movement is not obvious.  You have to stop moving bounce on the pirate platform, and thats how you make it across to the next section.  And I dealt with lazers by not spawning any.

**Comment by osse101** [comment]
Super Room
`canIframeSpikeJump` would be required for any of the requirements that are trying to save a spike hit without it imo, even just springball bouncing across.
`Damage boost speedball` is cool but I think the requirements and difficulty and runway length are similar enough to a speedKeep that both strats are not needed.
`2 to 5 to 4 to 1` can be assumed to be done by xray climbing `2 to 1` instead.
